/*
Auto-generated by gltfjsx, then enhanced with interactivity.
Author: dewa (https://sketchfab.com/dewa)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/teeth-3a0fb31b9d864b27a0846aca8579461c
*/

"use client";

import * as THREE from "three";
import { useMemo, useState, useCallback, useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { ThreeEvent } from "@react-three/fiber";
import { splitIntoIslands } from "./splitMesh";

type GLTFResult = GLTF & {
  nodes: {
    Object_3: THREE.Mesh;
    Object_4: THREE.Mesh;
    Object_5: THREE.Mesh;
    Object_6: THREE.Mesh;
    Object_7: THREE.Mesh;
    Object_8: THREE.Mesh;
  };
  materials: {
    Gums: THREE.MeshStandardMaterial;
    Teeth: THREE.MeshStandardMaterial;
    Tongue: THREE.MeshStandardMaterial;
  };
};

/**
 * Assigns US Universal tooth numbers (1-32) to geometry islands
 * based on their spatial position (bounding box center).
 *
 * Universal numbering:
 *   Upper right 1-8 (right to left from patient perspective)
 *   Upper left 9-16
 *   Lower left 17-24
 *   Lower right 25-32
 *
 * The model is rotated -PI/2 on X, so in local model space:
 *   X = left/right, Y = front/back, Z = up/down (upper vs lower jaw)
 */
function assignUniversalNumbers(
  islands: THREE.BufferGeometry[],
): { geo: THREE.BufferGeometry; toothNum: number }[] {
  // Compute center for each island
  const withCenters = islands.map((geo) => {
    geo.computeBoundingBox();
    const center = new THREE.Vector3();
    geo.boundingBox!.getCenter(center);
    return { geo, center };
  });

  // Split into upper (z > median z) and lower jaw
  const allZ = withCenters.map((i) => i.center.z);
  const medianZ = allZ.sort((a, b) => a - b)[Math.floor(allZ.length / 2)];

  const upper = withCenters.filter((i) => i.center.z >= medianZ);
  const lower = withCenters.filter((i) => i.center.z < medianZ);

  // Upper: sort right to left (descending X = patient's right first)
  // Universal 1 = upper right third molar, 16 = upper left third molar
  upper.sort((a, b) => b.center.x - a.center.x);

  // Lower: sort left to right (ascending X = patient's left first)
  // Universal 17 = lower left third molar, 32 = lower right third molar
  lower.sort((a, b) => a.center.x - b.center.x);

  const result: { geo: THREE.BufferGeometry; toothNum: number }[] = [];

  // Map upper islands to 1..16
  const upperStep = upper.length > 0 ? 16 / upper.length : 1;
  upper.forEach((item, i) => {
    const num = Math.round(1 + i * upperStep);
    result.push({ geo: item.geo, toothNum: Math.min(num, 16) });
  });

  // Map lower islands to 17..32
  const lowerStep = lower.length > 0 ? 16 / lower.length : 1;
  lower.forEach((item, i) => {
    const num = Math.round(17 + i * lowerStep);
    result.push({ geo: item.geo, toothNum: Math.min(num, 32) });
  });

  return result;
}

interface TeethModelProps {
  onToothSelect?: (toothNumber: number, worldPos: THREE.Vector3) => void;
  selectedTooth?: number | null;
  toothColors?: Record<number, string>;
}

export default function TeethModel({
  onToothSelect,
  selectedTooth,
  toothColors = {},
}: TeethModelProps) {
  const { nodes } = useGLTF("/models/teeth.glb") as unknown as GLTFResult;

  // Split the two teeth meshes into individual tooth islands
  // Filter out tiny fragments that cause double-selection
  const toothIslands = useMemo(() => {
    const islands6 = splitIntoIslands(nodes.Object_6.geometry);
    const islands7 = splitIntoIslands(nodes.Object_7.geometry);
    const allIslands = [...islands6, ...islands7].filter((geo) => {
      // Filter out fragments with very few triangles
      const indexCount = geo.index ? geo.index.count : 0;
      return indexCount > 50;
    });
    return assignUniversalNumbers(allIslands);
  }, [nodes]);

  return (
    <group dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={4.135}>
        <group position={[-0.262, -0.314, 4.671]}>
          {/* Gums - light holographic blue (raycast disabled) */}
          {[nodes.Object_3, nodes.Object_4, nodes.Object_5].map((node, i) => (
            <mesh key={`gum-${i}`} geometry={node.geometry} raycast={() => null}>
              <meshPhysicalMaterial
                color="#4a7aaa"
                transparent
                opacity={0.3}
                roughness={0.2}
                metalness={0.6}
                emissive="#5a90c0"
                emissiveIntensity={0.4}
                side={THREE.DoubleSide}
              />
            </mesh>
          ))}

          {/* Individual teeth - holographic */}
          {toothIslands.map(({ geo, toothNum }) => (
            <ToothMesh
              key={toothNum}
              geometry={geo}
              toothId={toothNum}
              isSelected={selectedTooth === toothNum}
              onSelect={onToothSelect}
              conditionColor={toothColors[toothNum]}
            />
          ))}

          {/* Tongue - holographic, mostly hidden (raycast disabled) */}
          <mesh geometry={nodes.Object_8.geometry} raycast={() => null}>
            <meshPhysicalMaterial
              color="#3a6090"
              transparent
              opacity={0.15}
              roughness={0.3}
              metalness={0.6}
              emissive="#4a80b0"
              emissiveIntensity={0.2}
            />
          </mesh>
        </group>
      </group>
    </group>
  );
}

interface ToothMeshProps {
  geometry: THREE.BufferGeometry;
  toothId: number;
  isSelected: boolean;
  onSelect?: (id: number, worldPos: THREE.Vector3) => void;
  conditionColor?: string;
}

function ToothMesh({ geometry, toothId, isSelected, onSelect, conditionColor }: ToothMeshProps) {
  const meshRef = useRef<THREE.Mesh>(null);
  const [hovered, setHovered] = useState(false);

  const handleClick = useCallback(
    (e: ThreeEvent<MouseEvent>) => {
      e.stopPropagation();
      // Get the world-space center of this tooth
      const mesh = meshRef.current;
      if (mesh) {
        const box = new THREE.Box3().setFromObject(mesh);
        const center = new THREE.Vector3();
        box.getCenter(center);
        onSelect?.(toothId, center);
      } else {
        onSelect?.(toothId, e.point);
      }
    },
    [onSelect, toothId],
  );

  const handlePointerOver = useCallback((e: ThreeEvent<PointerEvent>) => {
    e.stopPropagation();
    setHovered(true);
    document.body.style.cursor = "pointer";
  }, []);

  const handlePointerOut = useCallback(() => {
    setHovered(false);
    document.body.style.cursor = "default";
  }, []);

  // If tooth has a condition, use that color; otherwise default holographic blue
  const hasCondition = !!conditionColor;
  const isMissing = conditionColor === "#6B7280";
  const baseColor = conditionColor || "#7cc4f0";
  const baseEmissive = conditionColor || "#5ab0e8";

  const emissiveIntensity = isSelected ? 1.4 : hovered ? 1.0 : isMissing ? 0.2 : hasCondition ? 0.9 : 0.7;
  const color = isSelected ? "#88eeff" : hovered ? baseColor : baseColor;
  const emissive = isSelected ? "#66eeff" : hovered ? baseEmissive : baseEmissive;
  const opacity = isSelected ? 0.9 : hovered ? 0.8 : isMissing ? 0.2 : hasCondition ? 0.75 : 0.6;

  return (
    <mesh
      ref={meshRef}
      geometry={geometry}
      onClick={handleClick}
      onPointerOver={handlePointerOver}
      onPointerOut={handlePointerOut}
    >
      <meshPhysicalMaterial
        color={color}
        emissive={emissive}
        emissiveIntensity={emissiveIntensity}
        transparent
        opacity={opacity}
        roughness={0.1}
        metalness={0.9}
        clearcoat={1}
        clearcoatRoughness={0.05}
        side={THREE.DoubleSide}
      />
    </mesh>
  );
}

useGLTF.preload("/models/teeth.glb");
